---
title: "Class05"
author: "David Majeed (PID:A17885958)"
format: pdf
editor: visual
---

# Class 5 Data Visualization Lab

Questions from Website:

Q1. All the above

Q2. False

Q3. Network Graphs

Q4. ggplot is the only way to create plots in R

Q5. geom_point()

Q6. 5196

Q7. 4

Q8. 127

Q9. 2.44

```{r}
#install.packages("ggplot2")
#This installs the software
library(ggplot2)
#To make sure R knows where to look

View(cars)
#view the data set

plot(cars)
#this is the default plotting software

ggplot(data=cars)+
  aes(x=speed, y=dist) + geom_point()

p <- ggplot(data=cars)+ aes(x=speed, y=dist) + geom_point()

#ggplot() is how we get R to start the function, the (data=cars) has R use the cars data as the data for the graph, the connects the lines rows to one another so we don't have one long line of code, aes() is for the aesthics of graph, geom_point() determines the type of graph such as scatter, p just to put it all in one variable
```

```{r}
#Add a trend line close to the data through adding the geom_smooth(). Each subsequent argument adds different elements such as method="lm", se=FALSE which adds a straight line 
p+geom_smooth()
p+geom_smooth(method="lm", se=F)

#labs() adds titles and lables tp pur data, and theme_bw() adds a theme to color our graph

p+geom_smooth(method="lm", se=F)+
labs(title="Speed and Stopping Distances of Cars", x="Speed (MPH)",y="Stopping Distance (ft)", caption="Dataset: 'cars'")+
  theme_bw()
```

```{r}
url <- "https://bioboot.github.io/bimm143_S20/class-material/up_down_expression.txt"

#loads our outside data into a variable we can load in r

genes <- read.delim (url) 
#allows us to read the url through the genes variable

head(genes)
#gives the first part of the data


```

```{r}
#Let's make a first plot attempt
 g <- ggplot(genes)+ aes(x=Condition1, y=Condition2, col=State)+ geom_point()
 g
 
 #ggplot(genes) allows us to use our data stored in gene, aes gives us control to plot x and y, col gives us the ability to color by state, geom_point() creates a scatter plot. Let's actually customize this
  g + scale_color_manual(values=c("magenta", "yellow", "pink"))
 
 
 #Lab settings
 
 g+ scale_color_manual(values=c("blue", "gray", "red")) + labs(title="Gene expresion changes", x="Control(no drug)", y="Drug Treatment")+ theme_bw()
 
 #values gives color to the options, labs adds the titles, and theme adds a theme
 
```

```{r}
#lets get data out of this data set
#How many genes in the data set?
nrow(genes)
colnames(genes)
ncol(genes)
#How many up regulated genes?
table(genes$State)
#Fraction of total genes are upregulated
round((table(genes$State)/nrow(genes))*100, 2)
```

## Beyond

```{r}
#install.packages("gapminder")
library(gapminder)
#install.packages("dplyr") 
library(dplyr)
gapminder_2007 <- gapminder %>% filter(year==2007)

ggplot(gapminder_2007)+ aes(x=gdpPercap, y=lifeExp,color=continent, size=pop)+ geom_point(alpha=0.5)

ggplot(gapminder_2007) + geom_point(aes(x = gdpPercap, y = lifeExp, size = pop), alpha=0.5) + scale_size_area(max_size = 10)

gapminder_1957<- gapminder %>% filter(year==1957) 

ggplot(gapminder_1957)+ aes(x=gdpPercap, y=lifeExp,color=continent, size=pop)+ geom_point(alpha=0.7) +scale_size_area(max_size = 15)+facet_wrap(~year)

gapminder_top5 <- gapminder %>% 
  filter(year==2007) %>% 
  arrange(desc(pop)) %>% 
  top_n(5, pop)

gapminder_top5 

ggplot(gapminder_top5) + geom_col(aes(x = country, y = pop))

ggplot(gapminder_top5) + geom_col(aes(x = country, y = pop, fill = continent))

ggplot(gapminder_top5) + geom_col(aes(x = country, y = pop, fill = lifeExp))

ggplot(gapminder_top5) +
  geom_col(aes(x = country, y = pop, fill = gdpPercap)) 

ggplot(gapminder_top5) + 
  aes(x=reorder(country, -pop), y=pop, fill=gdpPercap) + 
  geom_col()

ggplot(gapminder_top5) + 
  aes(x=reorder(country, -pop), y=pop, fill=country) + 
  geom_col(col="gray30") + guides(fill="none")

head(USArrests)

USArrests$State <- rownames(USArrests) 

ggplot(USArrests) +
  aes(x=reorder(State,Murder), y=Murder) + 
  geom_col() +
  coord_flip() 

ggplot(USArrests) +
  aes(x=reorder(State,Murder), y=Murder) + 
  geom_point() + 
  geom_segment(aes(x=State, xend=State, y=0, yend=Murder), color="blue") + 
  coord_flip()
#install.packages("gifski") #install.packages("gganimate") library(gapminder)

library(gganimate)

ggplot(gapminder, aes(gdpPercap, lifeExp, size=pop, color=country))+ geom_point(alpha=0.7, show.legend = FALSE) + scale_color_manual(values = country_colors) + scale_size(range = c(2,12))+ scale_x_log10()+ facet_wrap(~continent)+ labs(title='Year: {frame_time}', x='GDP per cpaita', y='life expectancy')+ transition_time(year)+ shadow_wake(wake_length = 0.1, alpha = FALSE)

#install.packages("patchwork")

library(patchwork)
p1<- ggplot(mtcars)+geom_point(aes(mpg, disp)) 
p2<- ggplot(mtcars)+ geom_boxplot(aes(gear, disp, group = gear))
p3 <- ggplot(mtcars) + geom_smooth(aes(disp, qsec)) 
p4 <- ggplot(mtcars) + geom_bar(aes(carb)) 

(p1 | p2 | p3)/ p4

sessionInfo()
```
